---
project_name: fleet

before:
  hooks:
    - go mod download

archives:
  - id: fleet-controller
    format: binary
    name_template: "{{ .Binary }}"
    builds:
      - fleet-controller

  - id: fleet-agent
    format: binary
    name_template: "{{ .Binary }}"
    builds:
      - fleet-agent

  - id: fleet-gitcloner
    format: binary
    name_template: "{{ .Binary }}"
    builds:
      - fleet-gitcloner

  - id: fleet-gitjob
    format: binary
    name_template: "{{ .Binary }}"
    builds:
      - fleet-gitjob

  - id: fleet-cli
    format: binary
    name_template: "{{ .Binary }}"
    builds:
      - fleet-cli

builds:
  -
    id: fleet-controller
    main: ./cmd/fleetcontroller
    binary: fleetcontroller-{{ .Os }}-{{ .Arch }}{{ if .Arm }}64{{ end }}
    no_unique_dist_dir: true
    # gcflags:
    #   - all="-N -l"
    ldflags:
      - -w -s
      - -X github.com/weyfonk/fleet/pkg/version.GitCommit={{ .Commit }}
      - -X github.com/weyfonk/fleet/pkg/version.Version={{ .Tag }}
    targets:
    - windows_amd64
  -
    id: fleet-agent
    main: ./cmd/fleetagent
    binary: fleetagent-{{ .Os }}-{{ .Arch }}{{ if .Arm }}64{{ end }}
    no_unique_dist_dir: true
    ldflags:
      - -w -s
      - -X github.com/weyfonk/fleet/pkg/version.GitCommit={{ .Commit }}
      - -X github.com/weyfonk/fleet/pkg/version.Version={{ .Tag }}
    targets:
    - windows_amd64
  -
    id: fleet-gitcloner
    main: ./cmd/gitcloner
    binary: gitcloner-{{ .Os }}-{{ .Arch }}{{ if .Arm }}64{{ end }}
    no_unique_dist_dir: true
    ldflags:
      - -w -s
      - -X github.com/weyfonk/fleet/pkg/version.GitCommit={{ .Commit }}
      - -X github.com/weyfonk/fleet/pkg/version.Version={{ .Tag }}
    targets:
    - windows_amd64
  -
    id: fleet-gitjob
    main: ./cmd/gitjob
    binary: gitjob-{{ .Os }}-{{ .Arch }}{{ if .Arm }}64{{ end }}
    no_unique_dist_dir: true
    ldflags:
      - -w -s
      - -X github.com/weyfonk/fleet/pkg/version.GitCommit={{ .Commit }}
      - -X github.com/weyfonk/fleet/pkg/version.Version={{ .Tag }}
    targets:
    - windows_amd64
  -
    id: fleet-cli
    main: ./cmd/fleetcli
    binary: fleet-{{ .Os }}-{{ .Arch }}{{ if .Arm }}64{{ end }}
    no_unique_dist_dir: true
    ldflags:
      - -w -s
      - -X github.com/weyfonk/fleet/pkg/version.GitCommit={{ .Commit }}
      - -X github.com/weyfonk/fleet/pkg/version.Version={{ .Tag }}
    targets:
    - windows_amd64

changelog:
  ## Delegate Changelog to release-drafter
  disable: true
  use: github

env:
  - CGO_ENABLED=0

snapshot:
  name_template: "{{ .Tag }}-next"

dockers:
  # fleet-agent images
  -
    use: buildx
    goos: windows
    goarch: amd64
    ids:
    - fleet-agent
    - fleet-cli
    image_templates:
    - "ghcr.io/weyfonk/fleet-agent:{{ .Tag }}-windows-1809"
    dockerfile: package/Dockerfile-windows.agent
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source=https://github.com/weyfonk/fleet"
    - "--build-arg=WINDOWS_VERSION=1809"
    - "--platform=windows/amd64"
  -
    use: buildx
    goos: windows
    goarch: amd64
    ids:
    - fleet-agent
    - fleet-cli
    image_templates:
    - "ghcr.io/weyfonk/fleet-agent:{{ .Tag }}-windows-ltsc2022"
    dockerfile: package/Dockerfile-windows.agent
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source=https://github.com/weyfonk/fleet"
    - "--build-arg=WINDOWS_VERSION=ltsc2022"
    - "--platform=windows/amd64"

docker_manifests:
  # https://goreleaser.com/customization/docker_manifest/
  - name_template: "ghcr.io/weyfonk/fleet-agent:{{ .Tag }}"
    image_templates:
    - "ghcr.io/weyfonk/fleet-agent:{{ .Tag }}-linux-amd64"
    - "ghcr.io/weyfonk/fleet-agent:{{ .Tag }}-linux-arm64"
    - "ghcr.io/weyfonk/fleet-agent:{{ .Tag }}-windows-1809"
    - "ghcr.io/weyfonk/fleet-agent:{{ .Tag }}-windows-ltsc2022"
