ARG SERVERCORE_VERSION
FROM mcr.microsoft.com/windows/servercore:${SERVERCORE_VERSION}
USER ContainerUser
COPY fleetagent-windows-amd64.exe fleetagent-windows.exe
CMD ["C:\\fleet\\fleetagent-windows.exe"]
